author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /goop-tales
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
homepage_image: http://digital.library.wayne.edu/readux/books/wayne:Gooptale1904b51074709_Readux_VirtualVolume/pages/wayne:Gooptale1904b51074709_Readux_VirtualPage_1/single-page/
image_size:
  page:
    height: 1000
    width: 790
  small-thumbnail:
    height: 100
    width: 79
  thumbnail:
    height: 300
    width: 237
permalink: pretty
publication_info:
  author: Burgess, Gelett , 1866-1951
  date: '2016'
  editors: []
  tei_xml: tei.xml
  title: 'Goop tales alphabetically told: a study of the behavior of some fifty-two
    interesting individuals, each of which while mainly virtuous, yet has some one
    human & redeeming fault; with numerous illustrations, an annotated digital edition'
show_annotation_author: true
source_info:
  author: Burgess, Gelett , 1866-1951
  date: '1904'
  pdf_url: http://digital.library.wayne.edu/readux/books/wayne:Gooptale1904b51074709_Readux_VirtualVolume/pdf/
  title: 'Goop tales alphabetically told: a study of the behavior of some fifty-two
    interesting individuals, each of which while mainly virtuous, yet has some one
    human & redeeming fault; with numerous illustrations'
  url: http://digital.library.wayne.edu/readux/books/wayne:Gooptale1904b51074709_Readux_VirtualVolume/
  via_readux: true
tagline: ', an annotated digital edition'
title: 'Goop tales alphabetically told: a study of the behavior of some fifty-two
  interesting individuals, each of which while mainly virtuous, yet has some one human
  & redeeming fault; with numerous illustrations'
url: http://ghukill.github.io
version: 0.6
